settings:
  docker:
    parent_image: python:3.11-slim
    skip_build: False

parameters:
  zip_url: "$ZIP_URL"
  collection_name: "$VECTOR_COLLECTION_NAME"
  mongodb_connection_string: "$MONGODB_CONNECTION_STRING"
  qdrant_host: "$QDRANT_HOST"
  qdrant_port: "$QDRANT_PORT"