AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: RAG Data Processing

Globals:
  Function:
    Timeout: 900
    Runtime: python3.9

Resources:
  # S3 Bucket with notification configuration
  DataUploadsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DataUploadBucket
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt DataProcessingHandlerFunction.Arn

  # Lambda permission for S3 to invoke the function
  DataProcessingHandlerFunctionS3Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DataProcessingHandlerFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub "arn:aws:s3:::${DataUploadBucket}"

  # Data Processing Handler Lambda Function
  DataProcessingHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handler/
      Handler: app.lambda_handler
      Environment:
        Variables:
          PYTHONPATH: ./
          DATA_WORKFLOW_ARN: !Ref DataWorkflowArn
      Policies:
        - StepFunctionsExecutionPolicy:
            StateMachineName: !Ref DataWorkflowArn
        - S3ReadPolicy:
            BucketName: !Ref DataUploadBucket
        - Statement:
          - Effect: Allow
            Action:
              - states:StartExecution
            Resource: !Ref DataWorkflowArn

Parameters:
  DataUploadBucket:
    Type: String
    Description: Name of the S3 bucket for data uploads
  DataWorkflowArn:
    Type: String
    Description: ARN of the Data Processing Workflow State Machine